#ifndef TCLZMACHINE_H
#define TCLZMACHINE_H

/*
 * tclzmachine.h
 *
 * Central runtime definition for the Tcl Z-machine extension. The project is
 * intentionally text-only and supports Z-machine versions 1-5, 7, and 8.
 * Version 6 is excluded because its presentation model depends heavily on
 * pixel-positioned windows and graphics, which do not fit the IRC-oriented
 * runtime this project is designed to provide.
 */

#include <stddef.h>
#include <stdint.h>
#include <tcl.h>

#include "zmachine_state.h"
#include "zmachine_version.h"

#ifdef __cplusplus
extern "C" {
#endif

#define TCLZMACHINE_VERSION "0.2.0"
#define TCLZMACHINE_TEXT_ONLY 1

/* Coarse execution state visible to the Tcl-facing session layer. */
typedef enum ZMachineRunState {
    ZM_STATE_READY = 0,
    ZM_STATE_WAITING_INPUT,
    ZM_STATE_HALTED,
    ZM_STATE_ERROR
} ZMachineRunState;

/*
 * Complete per-session interpreter state. No ordinary VM state is global;
 * every Tcl session owns one ZMachine instance so many games can coexist in
 * one process without sharing stacks, memory, random state, or I/O buffers.
 */
struct ZMachine {
    /* Mutable story image. Dynamic memory is modified directly by Z-code. */
    uint8_t *memory;
    size_t memory_size;

    /* Original dynamic-memory bytes retained for the restart opcode. */
    uint8_t *initial_dynamic_memory;
    size_t initial_dynamic_memory_size;

    /* Cached fields from the story-file header. */
    uint8_t version;
    uint16_t flags1;
    uint16_t release_number;
    uint16_t high_memory_addr;
    uint16_t initial_pc;
    uint16_t dictionary_addr;
    uint16_t object_table_addr;
    uint16_t globals_addr;
    uint16_t static_memory_addr;
    uint16_t flags2;
    uint16_t abbreviations_addr;
    uint16_t header_file_length_word;
    size_t declared_file_length;
    uint16_t checksum;
    uint16_t routine_offset;
    uint16_t string_offset;
    uint16_t header_extension_addr;

    /* Program counter, evaluation stack, and routine call frames. */
    uint32_t pc;
    uint16_t stack[4096];
    size_t sp;
    ZMachineFrame frames[ZM_MAX_FRAMES];
    size_t frame_count;

    /* Per-session pseudo-random generator state used by the random opcode. */
    uint32_t random_state;

    /* Canonical output and one queued line of player input. */
    Tcl_DString output;
    Tcl_DString pending_input;
    int input_available;

    ZMachineRunState state;
    char error[256];
};

/* Lifetime and story-image management. */
ZMachine *zmachine_create(void);
void zmachine_destroy(ZMachine *vm);
int zmachine_load_story(ZMachine *vm, const char *path);
int zmachine_reset(ZMachine *vm);

/* Queue one command and execute until another input request, halt, or error. */
int zmachine_supply_input(ZMachine *vm, const char *line);
int zmachine_run(ZMachine *vm);

/* Version-aware packed-address conversion helpers. */
uint32_t zmachine_unpack_routine_address(const ZMachine *vm, uint16_t packed);
uint32_t zmachine_unpack_string_address(const ZMachine *vm, uint16_t packed);

/* Canonical, unwrapped textual output generated by the VM. */
void zmachine_output_clear(ZMachine *vm);
void zmachine_output_append(ZMachine *vm, const char *text, size_t len);
const char *zmachine_output_data(const ZMachine *vm);
int zmachine_output_length(const ZMachine *vm);

/* Last interpreter error for this session. */
const char *zmachine_last_error(const ZMachine *vm);

#ifdef __cplusplus
}
#endif

#endif
